### ISSUE TITLE
EAS2Text not actually giving me the counties???

### ISSUE THREAD

**Issue by Ariemakesthebest** [A-c0rN/EAS2Text#3]
So im working on a CG with my friend and i put in a valid fips code the code was 039089 and using the TRILITHIC mode it did not show up, It did not show up with the SAGE EAS mode either. I am going to try other modes but before i used trilithic i used DASDEC and i had no problem with it.. I Tried using entirety of florida fips codes and that did not work either. the ZCZC String is ZCZC-EAS-DMO-012000-3131930-EASyPLUS- code attached `    text = EAS2Text(sameData=zczc, mode="SAGE EAS", timeZone=-4)` `full = text.EASText + ". " + desc` output is A Broadcast station or cable system has issued a Practice/Demo Warning for  beginning at 03:30 pm Wed Nov 09 and ending at 01:50 am Fri Nov 11 (EASyPLUS).

**Comment by A-c0rN** [comment]
Alright, sorry for the long wait. Work do be like that.
You have an invalid EAS string, you’re missing the duration. Try adding +0015 in the ZCZC between the FIPS codes and the timestamps.

**Comment by A-c0rN** [comment]
ZCZC-EAS-DMO-012000+0015-3131930-EASyPLUS-

also, for the SAGE mode, the mode is just SAGE, not SAGE EAS.
